// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package cdaxbeat

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "cdaxbeat", asset.ModuleFieldsPri, AssetCdaxbeat); err != nil {
		panic(err)
	}
}

// AssetCdaxbeat returns asset data.
// This is the base64 encoded zlib format compressed contents of module/cdaxbeat.
func AssetCdaxbeat() string {
	return "eJx0kU1ugzAUhPc+xSj75ABe9Ai9QuXYA32KfxA2arl95aig2JDZIM3D8z7Nu+LBVcM683unKQooUjw1Lpt1UcBMT5OpcWcxCnDMdpapSIoaHwrAnoCQ3OKpgEHoXdbP6RXRBDZ7qso6UWOc0zL9OyfJ29tBPEOKt/qtTpPx4PqTZvc+perTBCINKN/E5JdRImzynrZIHKubicAyi823/VG3fvfP6Kv6rja9Yao6Rr9214MUCfxy9MWgmTdA/ajZnmlTdBlZoiW8yc+rySDW1B+2iipWF3PG1Zf0cpsjXHuno9RfAAAA///yFbOu"
}
