// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package my_module

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "my_module", asset.ModuleFieldsPri, AssetMyModule); err != nil {
		panic(err)
	}
}

// AssetMyModule returns asset data.
// This is the base64 encoded zlib format compressed contents of module/my_module.
func AssetMyModule() string {
	return "eJx8kLFuwzAMRHd9xSF7lo4a+iuBbNMVG8oUJBqB/76wEae1auQWATzo3ZFX3GnxSMst6TALOcDYhDwur9nFAYWEQiWPjiw4YKDaF87GOnl8OgC/DDwfrsihGHSERUIiK9x3FAwPLfcaNePDASOTDNVvjCumkOjYZ5UtmTy+is75OTkpcET9xY0sdEs6vYwz4qp2zV2naXvmP3Zbo61SD87eRbtv6q2x3gRvPyNtxJVd8WCLGGcR5GBxv/uWCIvr3VkESSc2LTS4nwAAAP//lp2Rag=="
}
