// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package my_module

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "my_module", asset.ModuleFieldsPri, AssetMyModule); err != nil {
		panic(err)
	}
}

// AssetMyModule returns asset data.
// This is the base64 encoded zlib format compressed contents of module/my_module.
func AssetMyModule() string {
	return "eJyckDFuhTAQRHufYkRPk9JFrhIZGIKFjS17UcTtIxIMycfF13+N5S1m522LmZuG3z58GFZHBYgVR43mnDUKSHQ0mRodxShgYO6TjWLDovGuAFwZOB6bEU0ShBEyEZ6SbN/RCL5CmvMUIt4UMFq6IeufjBaL8fzfZ0e2SI3PFNZ4TCoFrqjju+fd9ApVzcKjbqG69ZdX9Qt/z3DVr5/jdLid5Ymi91XqOwAA//9j7pKV"
}
